language: node_js
node_js:
    - 10
cache:
    directories:
        - node_modules
script:
    - npm run build
    - npm test
    - npm run test:coveralls
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5da67ea6192509e5095bc6ac
